micronaut:
  application:
    name: demo
  server:
    port: 9090
datasources:
  default:
    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
clinic:
  name: Micronaut Clinic
  pets:
    fred:
      name: Fred
      age: 8
    bob:
      name: Bob
      age: 5